services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - Backend